### PR TITLE
[HB-5620]: Amazon Publisher Services Rewarded Support

### PR DESCRIPTION
**Pull request by cb-jpadilla**
- Added support for rewarded placements.

### CODE REVIEW

**Review by CB-RyanMcCormick — APPROVED** [review]
This seems fine, but I can't find Amazon's documentation for `onVideoCompleted`

**Comment by cb-jpadilla** [comment]
> This seems fine, but I can't find Amazon's documentation for `onVideoCompleted`

It's found in their `DTBAdVideoListener` class from which their interstitial listener extends from it. 😃 

image

**Comment by CB-RyanMcCormick** [comment]
> > This seems fine, but I can't find Amazon's documentation for `onVideoCompleted`
> 
> It's found in their `DTBAdVideoListener` class from which their interstitial listener extends from it. 😃
> 
> image

Thanks. It's weird that it isn't in their integration docs.

**Comment by cb-jpadilla** [comment]
> > > This seems fine, but I can't find Amazon's documentation for `onVideoCompleted`
> > 
> > 
> > It's found in their `DTBAdVideoListener` class from which their interstitial listener extends from it. 😃
> > image
> 
> Thanks. It's weird that it isn't in their integration docs.

Right? 😄

**Review by chauduyphanvu — APPROVED** [review]

**Comment by bichenwang** [comment]
don't forget that one of y'all working on amazon gotta do the version bump at some point to publish a new version ^_^

**Comment by CB-RyanMcCormick** [comment]
> don't forget that one of y'all working on amazon gotta do the version bump at some point to publish a new version ^_^

I'll create the cert ticket and publish when QA approves

**Comment by cb-jpadilla** [comment]
Oh, let me know if I you want me to take a peek at it, @CB-RyanMcCormick 😃

**Pull request merged**
